project:
  type: book

book:
  title: "pm_book"
  author: "Igor Veksler"
  date: "12/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - economic_principles.qmd
    - summary.qmd
    - foundations.qmd
    - partnership_model.qmd
    - people_management.qmd
    - processes.qmd
    - design.qmd
    - additional_lessons_principles
    - analytics.qmd
    - forecasting.qmd
    - anti_patterns.qmd 
    - references.qmd



bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



