project:
  type: book

book:
  title: "pm_book"
  author: "Igor Veksler"
  date: "12/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - pm_traps.qmd 
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



