# Introduction

This project originally started as a [collection of product management links](https://github.com/iveksl2/product_management_links) I would collect in transitioning from a data scientist to a product manager. Given my background, the implicit motivation was using these principles as a foundation toward building a product building machine. You will see throughout this book, it my view that there is a lot of overlap between being product manager and being a CEO. Therefore broader enterpereneurhisp and economic concpets are very helpful to product managers.

After working at Weights and Biases that stresses the value of good writing, or peraphs being an academic at heart, I decided to make these collection of links to a longer form e-book to refine the ideas and surface and gaps in my own knoweldge. I hope others embarking on a career in product management will find some of the ideas helpful. Steal and bring into their own game only the you find useful. 

Principles, like assumptions, are meant to be challenged, discussed and debated and it through this refinement process that they are in fact strenghted. This is to say feel free to reach out discuss these more. To quote [Hugo Ponte](https://twitter.com/hupobuboo) ```"violent opposition"``` is welcomed.

This wiki will also contain perspectives from some of the best people I have worked with in the respective domain.

Although i have learned so many tips and tricks from too many to list, a few people I have observed and worked with disproportionally influeced my thinking 

### Acknowledgements & Influences
 * Jeremy Achin 
   * The best entreprenuer & product manager I have ever worked with.
* Gourab De
   * The best people manager I have worked with.
 * Ina Ko
   * Welcomed my to transition to her team as a PM and learned the most from when starting out as a PM. Also was the best boss I had within product management.
 * Lukas Biewald (CEO of Weights and Biases and successful 2X entrepenuer)
   * Thanks for emphasizing the value of writing. Ive taken some of my ideas through his public interviews on the Gradient Dissent Podcast and observing from afar. 


#### Other Work
Do you find some of this interesting? Are you also interested in Artificial Intelligence? Check out my other educational [wiki book on data science and artificial intelligence](https://iveksl2.github.io/ds_book/)!

